### ISSUE TITLE
youtube url

### ISSUE THREAD

**Issue by martingg88** [tusharmath/mtd-console#3]
seem like it doesn't download youtube mp4 video. You can try with following link and it doesn't work. any idea? FYI. the following link will work with wget. Maybe we need the --no-check-certificate option?

https://lh3.googleusercontent.com/xTMukQfobC193nsiO3K78vhxoaLyt5trzxOk4V3Wmw=m18

**Comment by tusharmath** [comment]
This will get resolved once [HTTPS support](https://github.com/tusharmath/Multi-threaded-downloader/issues/40) is provided.
